using from './template-service';
using from './util/common-service';
using from './util/org-service';
using {xx as sampleGrpMgr} from './sampleGrpMgr-service';
using {xx as sampleMgr} from './sampleMgr-service';
using {xx as sampleMstMgr} from './sampleMstMgr-service';
using from './testTable-service';
using {xx as variantManagement} from './variantManagement-service';
using from './sampleSession-service';
using from './sampleV2Test-service';