/** https://vscode-sqltools.mteixeira.dev/features/codelens */
-- @conn sppDb_hdi_dev_RT-en

-- @block Bookmarked query
-- @group SP_SC
-- @name #SessionContext
-- @conn sppDb_hdi_dev_RT-en
-- @table M_SESSION_CONTEXT
SELECT TOP 50 key,value,current_user
,* 
FROM M_SESSION_CONTEXT WHERE 1=1
AND CONNECTION_ID = current_connection
-- AND FIELD = "VALUE"
;

-- @block Bookmarked query
-- @group SP_SC
-- @conn sppDb_hdi_dev_RT-en
-- @name sp_Sc_Nego_Parent_Type_Code
select * from sp_Sc_Nego_Parent_Type_Code;


-- @block Bookmarked query
-- @group SP_SC
-- @conn sppDb_hdi_dev_RT-ko
-- @name sp_Sc_Nego_Parent_Type_Code
select * from sp_Sc_Nego_Parent_Type_Code;

-- @block Bookmarked query
-- @group SP_SC
-- @conn sppDb_hdi_dev_RT-en
-- @name sp_Sc_Nego_Parent_Type_Code_texts
select * from sp_Sc_Nego_Parent_Type_Code_texts;

-- @block Bookmarked query
-- @group SP_SC
-- @name #SessionContext
-- @table M_SQL_PLAN_CACHE
SELECT TOP 50 *
FROM M_SQL_PLAN_CACHE WHERE 1=1
AND upper(statement_string) like upper('%sp_Sc_Nego_Parent_Type_Code%')
-- AND FIELD = "VALUE"
;

-- @block Bookmarked query
-- @group SP_SC
-- @name #SessionContext
-- @table M_EXECUTED_STATEMENTS
SELECT TOP 50 *
FROM M_EXECUTED_STATEMENTS WHERE 1=1
AND CONNECTION_ID = current_connection
-- AND FIELD = "VALUE"
;
-- @block Bookmarked query
-- @group Common
-- @name Contents to Csv
DO BEGIN
DECLARE OBJECT_NAME NVARCHAR(255) DEFAULT 'SP_SC_NEGOTIATION_STYLE_CODE_TEXTS';
DECLARE SQL_STRING NVARCHAR(3000) DEFAULT '';
DECLARE STRING_CSV NVARCHAR(9000) DEFAULT '';
DECLARE CREATED INT DEFAULT 0;
SQL_STRING = 'EXPORT '||OBJECT_NAME||' AS CSV INTO "#CLIENT_EXPORT_1585101237059" WITH REPLACE NO DEPENDENCIES THREADS 8' ;
CREATED := 0;
SELECT COUNT(*) INTO CREATED FROM M_TEMPORARY_TABLES 
WHERE SCHEMA_NAME = CURRENT_SCHEMA AND CONNECTION_ID = CURRENT_CONNECTION 
AND TABLE_NAME = '#CLIENT_EXPORT_1585101237059' AND IS_TEMPORARY = 'TRUE';
IF (:CREATED > 0) THEN
	DROP TABLE #CLIENT_EXPORT_1585101237059;
END IF;
CREATE LOCAL TEMPORARY TABLE "#CLIENT_EXPORT_1585101237059" (FILENAME VARCHAR(64), PATH VARCHAR(255), CONTENT CLOB);
--EXEC 'EXPORT SP_SC_EVALUATION_TYPE_CODE AS CSV INTO "#CLIENT_EXPORT_1585101237059" WITH REPLACE NO DEPENDENCIES THREADS 8' ;
EXEC SQL_STRING;
-- SELECT CONTENT FROM #CLIENT_EXPORT_1585101237059 WHERE FILENAME = 'data.csv';
--#######################################################################
WITH OBJECT_COLUMNS AS (
SELECT OBJECT_TYPE, SCHEMA_NAME, OBJECT_NAME, COLUMN_NAME, POSITION, COMMENTS FROM (
    SELECT 'TABLE' OBJECT_TYPE, SCHEMA_NAME, TABLE_NAME OBJECT_NAME, COLUMN_NAME, POSITION, COMMENTS FROM "PUBLIC"."TABLE_COLUMNS" UNION ALL
    SELECT 'VIEW'  OBJECT_TYPE, SCHEMA_NAME, VIEW_NAME OBJECT_NAME, COLUMN_NAME, POSITION, COMMENTS FROM "PUBLIC"."VIEW_COLUMNS" 
) ORDER BY OBJECT_TYPE, SCHEMA_NAME, OBJECT_NAME, POSITION )
, OBJECT_COLUMN_HEADER AS (
--SELECT * FROM OBJECT_COLUMNS WHERE
SELECT STRING_AGG(ESCAPE_DOUBLE_QUOTES(COLUMN_NAME), ',' ORDER BY POSITION) AS COLUMN_HEADER
FROM OBJECT_COLUMNS WHERE OBJECT_NAME = :OBJECT_NAME
GROUP BY OBJECT_TYPE, SCHEMA_NAME, OBJECT_NAME )
, OBJECT_COLUMN_DATA AS ( SELECT CONTENT COLUMN_DATA FROM #CLIENT_EXPORT_1585101237059 WHERE FILENAME = 'data.csv' )
--#######################################################################
SELECT COLUMN_HEADER||char(10)||COLUMN_DATA FROM OBJECT_COLUMN_HEADER, OBJECT_COLUMN_DATA;
END;


