# Local PC : cds serve all --with-mocks --in-memory?
@serviceUrl = http://localhost:4004
# Local PC : mvn spring-boot:run : v2
@serviceUrl = http://localhost:8080/odata/v2
# Cloud Container Service : sppCap
@serviceUrl = https://lgcommondev-workspaces-ws-ll5cb-app1.jp10.applicationstudio.cloud.sap
# Cloud Container Service : sppCap
@serviceUrl = https://lg-clu-lgcommondev-msa1-sppcap-srv-dev.cfapps.jp10.hana.ondemand.com
# Local PC : mvn spring-boot:run : v4
@serviceUrl = http://localhost:8080/odata/v4
 
# @reviews-service = {{bookshop}}/sp.negoHeadersV4Service
# Uncomment this when running a separate reviews service
# Odata v2 service
@reviews-service = {{serviceUrl}}/sp.sourcingService
# Odata v4 service
@reviews-service = {{serviceUrl}}/sp.sourcingTest01V4Service

### Need a Cookie for credential not in local
# https://lg-clu-lgcommondev-msa1-sppcap-srv-dev.cfapps.jp10.hana.ondemand.com/
@cookie = JTENANTSESSIONID_services=5fZp7Tlz85JCf51p0PLyDiYoWX3fugTkSnF61L2Fb%2BU%3D
# https://lgcommondev-workspaces-ws-bhnz4-app2.jp10.applicationstudio.cloud.sap/
@cookie = workspaces-ws-ll5cb_WSR_SESSIONID=l29o4E9wu3PwAfEjhmtMpz70gsMR9MQmJ3RmtUxhKRT2V+Vlwtrw7Tgo1lGyBzodAPxXU52Efga/NZzmtSaoLA==
# for LG spp Dev Server
@cookie = 

### Ping Test
GET https://lg-clu-lgcommondev-msa1-sppcap-srv-dev.cfapps.jp10.hana.ondemand.com/odata/v4/cm.ControlOptionMgtService/ControlOptionMasters
Cookie: {{cookie}}

### Ping Test
GET http://localhost:8080/odata/v4/sp.sourcingTest01V4Service/$metadata

### Get Metadata for Service
GET {{reviews-service}}/$metadata

#################################################
#
#   NegoHeaders Service / Draft Service / Odata Commit
#   (draftActivate|draftPrepare|draftEdit|\bPUT\b|\bPOST\b|\bDELETE\b|\bPATCH\b)
### HDB Draft Metadata
# select * from "DRAFT_DRAFTADMINISTRATIVEDATA";
# select * from "SP_SOURCINGTEST01V4SERVICE_DRAFTADMINISTRATIVEDATA";
# select * from tables where upper(table_name) like upper('%SP_SOURCING%DRAFT%');
# select * from "SP_SOURCINGTEST01V4SERVICE_NEGOHEADERSTEST04";
# select * from "SP_SOURCINGTEST01V4SERVICE_NEGOHEADERSTEST04_DRAFTS";

### Multi Select
# /NegoHeadersTest04?&$count=true&$filter=(IsActiveEntity eq false or SiblingEntity/IsActiveEntity eq null)&$select=HasActiveEntity,tenant_id,IsActiveEntity&$expand=SiblingEntity,DraftAdministrativeData
GET {{reviews-service}}/NegoHeadersTest04?&$count=true
&$filter=((IsActiveEntity eq false or SiblingEntity/IsActiveEntity eq null) and (nego_header_id eq 2 or nego_header_id eq 3))
&$select=tenant_id,nego_header_id,nego_document_round,HasActiveEntity,IsActiveEntity,SiblingEntity,DraftAdministrativeData
&$expand=SiblingEntity,DraftAdministrativeData
Cookie: {{cookie}}
# &$skip=0&$top=30
# &$count=true

### Single Draft | Edit : Copy from Activate to Draft
POST {{reviews-service}}/NegoHeadersTest04(tenant_id='L2100',nego_header_id=3,IsActiveEntity=true)/sp.SourcingTest01V4Service.draftEdit?
&$select=tenant_id,nego_header_id,nego_document_round,HasActiveEntity,HasDraftEntity,IsActiveEntity
&$expand=DraftAdministrativeData($select=DraftUUID,InProcessByUser)
Cookie: {{cookie}}

{"PreserveChanges":true}

### Multi Select | $filter=(nego_header_id eq 2 or nego_header_id eq 3)
# /NegoHeadersTest04?&$count=true&$filter=(IsActiveEntity eq false or SiblingEntity/IsActiveEntity eq null)&$select=HasActiveEntity,tenant_id,IsActiveEntity&$expand=SiblingEntity,DraftAdministrativeData
GET {{reviews-service}}/NegoHeadersTest04?&$count=true
# &$filter=((IsActiveEntity eq false or SiblingEntity/IsActiveEntity eq null) and (nego_header_id eq 2 or nego_header_id eq 3))
&$filter=((nego_header_id eq 2 or nego_header_id eq 3))
&$select=tenant_id,nego_header_id,nego_document_round,HasActiveEntity,IsActiveEntity,SiblingEntity,DraftAdministrativeData
&$expand=SiblingEntity,DraftAdministrativeData
Cookie: {{cookie}}
# &$skip=0&$top=30
# &$count=true

### Single Update | Draft 
PATCH {{reviews-service}}/NegoHeadersTest04(tenant_id='L2100',nego_header_id=3,IsActiveEntity=false)
Content-Type: application/json

{
    "tenant_id": "L2100",
    "nego_header_id": 3,
    "operation_unit_code": "",
    "reference_nego_header_id": 3,
    "previous_nego_header_id": 0,
    "nego_document_round": 1,
    "local_create_dtm": "2021-01-11T19:29:17Z",
    "local_update_dtm": "2021-01-11T19:29:17Z",
    "create_user_id": "anonymous",
    "update_user_id": "anonymous",
    "system_create_dtm": "2021-01-11T10:29:17Z",
    "system_update_dtm": "2021-01-11T10:29:17Z"
}

### Multi Select | $filter=(nego_header_id eq 2 or nego_header_id eq 3)
# /NegoHeadersTest04?&$count=true&$filter=(IsActiveEntity eq false or SiblingEntity/IsActiveEntity eq null)&$select=HasActiveEntity,tenant_id,IsActiveEntity&$expand=SiblingEntity,DraftAdministrativeData
GET {{reviews-service}}/NegoHeadersTest04?&$count=true
# &$filter=((IsActiveEntity eq false or SiblingEntity/IsActiveEntity eq null) and (nego_header_id eq 2 or nego_header_id eq 3))
&$filter=((nego_header_id eq 2 or nego_header_id eq 3))
&$select=tenant_id,nego_header_id,nego_document_round,HasActiveEntity,IsActiveEntity,SiblingEntity,DraftAdministrativeData
&$expand=SiblingEntity,DraftAdministrativeData
Cookie: {{cookie}}
# &$skip=0&$top=30
# &$count=true

### Single Select | Active
GET {{reviews-service}}/NegoHeadersTest04(tenant_id='L2100',nego_header_id=3,IsActiveEntity=true)
Cookie: {{cookie}}

### Single Select | Draft
GET {{reviews-service}}/NegoHeadersTest04(tenant_id='L2100',nego_header_id=3,IsActiveEntity=false)
Cookie: {{cookie}}

### Draft Action | draftPrepare
POST {{reviews-service}}/NegoHeadersTest04(tenant_id='L2100',nego_header_id=3,IsActiveEntity=false)/sp.SourcingTest01V4Service.draftPrepare
Accept:application/json;odata.metadata=minimal;IEEE754Compatible=true
Accept-Language:ko
Content-Type:application/json;charset=UTF-8;IEEE754Compatible=true

{"SideEffectsQualifier":""}

### Multi Select | $filter=(nego_header_id eq 2 or nego_header_id eq 3)
# /NegoHeadersTest04?&$count=true&$filter=(IsActiveEntity eq false or SiblingEntity/IsActiveEntity eq null)&$select=HasActiveEntity,tenant_id,IsActiveEntity&$expand=SiblingEntity,DraftAdministrativeData
GET {{reviews-service}}/NegoHeadersTest04?&$count=true
&$filter=((nego_header_id eq 2 or nego_header_id eq 3))
&$select=tenant_id,nego_header_id,nego_document_round,HasActiveEntity,IsActiveEntity,SiblingEntity,DraftAdministrativeData
&$expand=SiblingEntity,DraftAdministrativeData
Cookie: {{cookie}}
# &$skip=0&$top=30
# &$count=true

### Draft Action | draftActivate
POST {{reviews-service}}/NegoHeadersTest04(tenant_id='L2100',nego_header_id=3,IsActiveEntity=false)/sp.SourcingTest01V4Service.draftActivate?$select=HasActiveEntity,HasDraftEntity,tenant_id,nego_header_id,nego_document_round,IsActiveEntity&$expand=DraftAdministrativeData($select=DraftUUID,InProcessByUser)
Accept:application/json;odata.metadata=minimal;IEEE754Compatible=true
Accept-Language:ko
Content-Type:application/json;charset=UTF-8;IEEE754Compatible=true

{}



### Multi Delete | No Available
DELETE {{reviews-service}}/NegoHeadersTest04?
&$filter=(nego_header_id eq 3)
# &$filter=(nego_header_id eq 3 or SiblingEntity/IsActiveEntity eq null)
Cookie: {{cookie}}
