# Local PC : cds serve all --with-mocks --in-memory?
@serviceUrl = http://localhost:4004
# Local PC : mvn spring-boot:run : v2
@serviceUrl = http://localhost:8080/odata/v2
# Cloud App Container Service : sppCap
@serviceUrl = https://lg-clu-lgcommondev-msa1-sppcap-srv-dev.cfapps.jp10.hana.ondemand.com
# Cloud BAS Container Workspace Service : sppCap
@serviceUrl = https://lgcommondev-workspaces-ws-ll5cb-app1.jp10.applicationstudio.cloud.sap
# Local PC : mvn spring-boot:run : v4
@serviceUrl = http://localhost:8080/odata/v4

# @reviews-service = {{bookshop}}/sp.negoHeadersV4Service
# Uncomment this when running a separate reviews service
# Odata v2 service
@reviews-service = {{serviceUrl}}/sp.negoHeadersService
# Odata v4 service
@reviews-service = {{serviceUrl}}/sp.negoHeadersV4Service

### User session credential cookie is required if not local server
# https://lg-clu-lgcommondev-msa1-sppcap-srv-dev.cfapps.jp10.hana.ondemand.com/
@cookie = 
# https://lgcommondev-workspaces-ws-bhnz4-app2.jp10.applicationstudio.cloud.sap/
@cookie = workspaces-ws-bhnz4_WSR_SESSIONID=Suul34z22XoXRlxYluU9QksQxt8qigb2ta2/lfMddWFIULR6WT0dlXHk360aRnC26I8LsXkRuewqAPbJIwQ22A==
# In Localserver
@cookie = 

### Test
GET https://lg-clu-lgcommondev-msa1-sppcap-srv-dev.cfapps.jp10.hana.ondemand.com/odata/v4/cm.ControlOptionMgtService/ControlOptionMasters
Cookie: {{cookie}}

#################################################
#
#   NegoHeaders Service
#

### Multi Select
GET {{reviews-service}}/NegoHeaders?
&$filter=nego_header_id ge 1 and nego_header_id le 10
&$select=nego_header_id,tenant_id
Cookie: {{cookie}}

### Single Select
GET {{reviews-service}}/NegoHeaders(tenant_id='L2100',nego_header_id=1)
Cookie: {{cookie}}

### INSERT 
# https://cap.cloud.sap/docs/java/query-api#upsert
POST {{reviews-service}}/NegoHeaders
Cookie: {{cookie}}
Content-Type: application/json

{
    "@context": "$metadata#NegoHeaders/$entity",
    "@metadataEtag": "W/\"5e7428872dee832e8ec4b5922458f509d034598aadb4f707bdf50b501b5b8d78\"",
    "tenant_id": "L2100",
    "nego_header_id": 1,
    "reference_nego_header_id": null,
    "previous_nego_header_id": null,
    "operation_unit_code": "2070:여수 ABS1",
    "reference_nego_document_number": 1,
    "nego_document_round": 1,
    "nego_document_number": "1-1",
    "nego_document_title": "원재료 Negotiation 2021-004",
    "nego_document_desc": "현재Sprint#1에서 간단히 테스트를 위한 정보를 입력하였습니다.",
    "nego_progress_status_code": "Draft",
    "award_progress_status_code": "Not Awarded ",
    "reply_times": null,
    "supplier_count": 3,
    "nego_type_code": "RFQ",
    "negotiation_output_class_code": "Tentative Price",
    "buyer_empno": "A59986",
    "buyer_department_code": null,
    "immediate_apply_flag": null,
    "open_date": "2021-01-01T07:30:10Z",
    "closing_date": "2021-01-13T08:00:00Z",
    "auto_rfq": null,
    "items_count": 2,
    "itesm_count": 2,
    "negotiation_style_code": "Blind",
    "close_date_ext_enabled_hours": 6,
    "close_date_ext_enabled_count": 3,
    "actual_extension_count": 1,
    "remaining_hours": null,
    "note_content": "w6zCtcKcw6rCs8Kgw6zCncKYIMOtwpLCiMOswqfCiCDDrMK1wpzDrMKgwoDDrMKdwpggw6vCi8Kow6rCsMKA",
    "award_type_code": "Award By Lines",
    "target_amount_config_flag": null,
    "target_amount": null,
    "supplier_participation_flag": null,
    "partial_allow_flag": "N",
    "bidding_result_open_status_code": null,
    "local_create_dtm": "2021-01-11T19:29:17Z",
    "local_update_dtm": "2021-01-13T16:36:57Z",
    "create_user_id": "anonymous",
    "update_user_id": "anonymous",
    "system_create_dtm": "2021-01-11T09:59:13Z",
    "system_update_dtm": "2021-01-13T07:36:57Z"
}

### Single Update[Insert OR Update]
PATCH {{reviews-service}}/NegoHeaders(tenant_id='L2100',nego_header_id=1)
Content-Type: application/json

{
    "tenant_id": "L2100",
    "nego_header_id": 1,
    "reference_nego_header_id": 1,
    "previous_nego_header_id": 1,
    "nego_document_round": 1,
    "nego_document_number": "1-1",
    "local_create_dtm": "2021-01-11T19:29:17Z",
    "local_update_dtm": "2021-01-11T19:29:17Z",
    "create_user_id": "anonymous",
    "update_user_id": "anonymous",
    "system_create_dtm": "2021-01-11T10:29:17Z",
    "system_update_dtm": "2021-01-11T10:29:17Z"
}

### Single Update[Delete AND Insert]
PUT {{reviews-service}}/NegoHeaders(tenant_id='L2100',nego_header_id=1)
Content-Type: application/json

{
    "tenant_id": "L2100",
    "nego_header_id": 1,
    "reference_nego_header_id": 1,
    "previous_nego_header_id": 1,
    "nego_document_round": 1,
    "nego_document_number": "1-1",
    "local_create_dtm": "2021-01-11T19:29:17Z",
    "local_update_dtm": "2021-01-11T19:29:17Z",
    "create_user_id": "anonymous",
    "update_user_id": "anonymous",
    "system_create_dtm": "2021-01-11T10:29:17Z",
    "system_update_dtm": "2021-01-11T10:29:17Z"
}

### Single Select
GET {{reviews-service}}/NegoHeaders(tenant_id='L2100',nego_header_id=1)

### Single Delete
DELETE {{reviews-service}}/NegoHeaders(tenant_id='L2100',nego_header_id=1)

#################################################
#
#   NegoItemPrices Service
#
GET {{reviews-service}}/NegoItemPrices

### Insert Single
POST {{reviews-service}}/NegoItemPrices
Content-Type: application/json

{
    "tenant_id": "L2100",
    "nego_header_id": 1,
    "nego_item_number": "00001",
    "operation_org_code": "",
    "operation_unit_code": "",
    # "line_type_code": "",
    # "inventory_item_code": "",
    "item_type_code": "",
    "local_create_dtm": "2021-01-11T19:29:17Z",
    "local_update_dtm": "2021-01-11T19:29:17Z",
    "create_user_id": "anonymous",
    "update_user_id": "anonymous",
    "system_create_dtm": "2021-01-11T10:29:17Z",
    "system_update_dtm": "2021-01-11T10:29:17Z"
}


#################################################
#
#   NegoSuppliers Service
#
GET {{reviews-service}}/NegoSuppliers?
&$select=*
&$top=3

### Insert Single
POST {{reviews-service}}/NegoSuppliers
Content-Type: application/json

{
    "tenant_id": "L2100",
    "nego_header_id": 1,
    "nego_item_number": "00001",
    "item_supplier_sequence": "00001",
    "local_create_dtm": "2021-01-11T19:29:17Z",
    "local_update_dtm": "2021-01-11T19:29:17Z",
    "create_user_id": "anonymous",
    "update_user_id": "anonymous",
    "system_create_dtm": "2021-01-11T10:29:17Z",
    "system_update_dtm": "2021-01-11T10:29:17Z"
}


#################################################
#   NegoHeaders Service
#   NegoItemPrices Service
#   NegoSuppliers Service

### Single NegoHeaders
GET {{reviews-service}}/NegoHeaders?$format=json&$top=1
### Single NegoHeaders/NegoItemPrices
GET {{reviews-service}}/NegoItemPrices?$format=json&$top=1
### Single NegoHeaders/NegoItemPrices
GET {{reviews-service}}/NegoSuppliers?$format=json&$top=1
### Complex NegoHeaders + NegoItemPrices
GET {{reviews-service}}/NegoHeaders(tenant_id='L2100',nego_header_id=1)?
&$format=json
&$select=*,Items
&$expand=Items
### Complex NegoHeaders + NegoItemPrices Aster V4 Only
GET {{reviews-service}}/NegoHeaders(tenant_id='L2100',nego_header_id=1)/Items?
&$format=json
&$select=*
&$expand=*
### Complex NegoItemPrices + NegoHeaders
GET {{reviews-service}}/NegoItemPrices(tenant_id='L2100',nego_header_id=1,nego_item_number='00001')?
&$format=json
&$expand=Header
### Complex NegoItemPrices + NegoHeaders
GET {{reviews-service}}/NegoItemPrices?
&$format=json
&$select=*,Header
&$expand=Header
### Complex 
GET {{reviews-service}}/NegoHeaders(tenant_id='L2100',nego_header_id=1)/Items?
&$format=json
&$select=*
&$expand=Suppliers
### Complex 
GET {{reviews-service}}/NegoHeaders(tenant_id='L2100',nego_header_id=1)/Items(tenant_id='L2100',nego_header_id=1,nego_item_number='00001')/Suppliers?
&$format=json
&$select=*
&$expand=Item,Item/Header
### Complex # V4 Only
GET {{reviews-service}}/NegoHeaders(tenant_id='L2100',nego_header_id=1)/Items(tenant_id='L2100',nego_header_id=1,nego_item_number='00001')/Suppliers?
&$format=json
&$select=*
&$expand=Item($expand=Header)
