#################################################
# OData Sever Configuration
#################################################
###
# Cloud Container Service : sppCap Workspace
@serviceUrl = https://lgcommondev-workspaces-ws-ll5cb-app1.jp10.applicationstudio.cloud.sap
# Cloud Container Service : sppCap
@serviceUrl = https://lg-clu-lgcommondev-msa1-sppcap-srv-dev.cfapps.jp10.hana.ondemand.com
# Local PC : mvn spring-boot:run : v2
@serviceUrlV2 = http://localhost:8080/odata/v2
# Local PC[DB+AP] : cds serve all --with-mocks --in-memory?
@serviceUrl = http://localhost:4004
# Local PC : mvn spring-boot:run : v4
@serviceUrl = http://localhost:8080/odata/v4

#################################################
# OData Service Configuration
#################################################
# @reviews-service = {{bookshop}}/sp.negoHeadersV4Service
# Uncomment this when running a separate reviews service
# Odata v2 service
@reviews-serviceV2 = {{serviceUrlV2}}/sp.sourcingService
# Odata v4 service
@reviews-service = {{serviceUrl}}/sp.sourcingV4Service

#################################################
# OData Service Configuration
# Need not a Cookie for credential in local
#################################################
# https://lg-clu-lgcommondev-msa1-sppcap-srv-dev.cfapps.jp10.hana.ondemand.com/
@cookie = JTENANTSESSIONID_services=5fZp7Tlz85JCf51p0PLyDiYoWX3fugTkSnF61L2Fb%2BU%3D
# https://lgcommondev-workspaces-ws-bhnz4-app2.jp10.applicationstudio.cloud.sap/
@cookie = workspaces-ws-ll5cb_WSR_SESSIONID=l29o4E9wu3PwAfEjhmtMpz70gsMR9MQmJ3RmtUxhKRT2V+Vlwtrw7Tgo1lGyBzodAPxXU52Efga/NZzmtSaoLA==
# for LG spp Dev Server
@cookie = 

#################################################
# OData Ping Test
#################################################
### Ping Test : Deployed Server(DEV)
GET https://lg-clu-lgcommondev-msa1-sppcap-srv-dev.cfapps.jp10.hana.ondemand.com/odata/v4/cm.ControlOptionMgtService/ControlOptionMasters
Cookie: {{cookie}}

### Ping Test : Localhost
GET http://localhost:8080/odata/v4/sp.sourcingTest01V4Service/$metadata

### Get Metadata for Service
GET {{reviews-service}}/$metadata



#################################################
# OData Main Test #1
#   localized Master CRUD
#   (draftActivate|draftPrepare|draftEdit|\bPUT\b|\bPOST\b|\bDELETE\b|\bPATCH\b)
#################################################

### Multi Select | Default
GET {{reviews-service}}/Sc_Outcome_Code?$orderby=sort_no
&$expand=*
# &$filter=((IsActiveEntity eq false or SiblingEntity/IsActiveEntity eq null) and (nego_header_id eq 2 or nego_header_id eq 3))
# &$select=tenant_id,nego_header_id,nego_document_round,HasActiveEntity,IsActiveEntity,SiblingEntity,DraftAdministrativeData
# &$expand=SiblingEntity,DraftAdministrativeData
Cookie: {{cookie}}

### Multi Select | Expand All[Texts,Localized]
GET {{reviews-service}}/Sc_Outcome_Code?
&$expand=nego_type($expand=nego_parent_type($expand=*)),texts,localized
Cookie: {{cookie}}
Accept-Language: ko

### Multi Select | Expand All[Texts,Localized]
GET {{reviews-service}}/Sc_Outcome_Code?
&$expand=nego_type($expand=nego_parent_type($expand=*)),texts,localized
Cookie: {{cookie}}
Accept-Language: en

### Multi Select | "Outcome" Materialized[Select,Filter,Localized]-OrderBy=가격|비가격,협상유형,아웃컴
GET {{reviews-service}}/Sc_Outcome_Code?
&$orderby=nego_type/evaluation_type/sort_no,nego_type/sort_no,sort_no
&$select=sort_no,tenant_id,nego_type_code,outcome_code,outcome_name
&$expand=nego_type($select=sort_no,nego_type_name,evaluation_type;$expand=nego_parent_type($select=sort_no,nego_parent_type_name),evaluation_type($select=sort_no,evaluation_type_name))
Cookie: {{cookie}}
Accept-Language: ko

### Multi Select | "Outcome" Materialized[Select,Filter,Localized]-OrderBy=가격|비가격,협상유형,아웃컴-Compact
GET {{reviews-service}}/Sc_Outcome_Code?
&$orderby=nego_type/evaluation_type/sort_no,nego_type/sort_no,sort_no
&$select=tenant_id,nego_type_code,outcome_code,outcome_name
&$expand=nego_type($select=nego_type_name,evaluation_type;$expand=nego_parent_type($select=nego_parent_type_name),evaluation_type($select=evaluation_type_name))
Cookie: {{cookie}}
Accept-Language: ko

### Multi Select V2 | "Outcome" Materialized[Select,Filter,Localized]-OrderBy=가격|비가격,협상유형,아웃컴-Compact
GET {{reviews-serviceV2}}/Sc_Outcome_Code?$format=json
&$orderby=nego_type/evaluation_type/sort_no,nego_type/sort_no,sort_no
&$select=tenant_id,nego_type_code,nego_type/nego_type_name,outcome_code,outcome_name,nego_type/evaluation_type/evaluation_type_name
&$expand=nego_type,nego_type/evaluation_type
Cookie: {{cookie}}
Accept-Language: ko

### Multi Select | "Negotiation Type" Materialized[Select,Filter,Localized]-OrderBy=가격|비가격,협상유형,아웃컴-Compact
GET {{reviews-service}}/Sc_Nego_Type_Code?
&$orderby=evaluation_type/sort_no,sort_no
&$select=tenant_id,nego_type_code,nego_type_name,evaluation_type
&$expand=nego_parent_type($select=nego_parent_type_name),evaluation_type($select=evaluation_type_name)
Cookie: {{cookie}}
Accept-Language: ko

### Multi Select V2 | "Negotiation Type" Materialized[Select,Filter,Localized]-OrderBy=가격|비가격,협상유형,아웃컴-Compact
GET {{reviews-serviceV2}}/Sc_Nego_Type_Code?$format=json
&$orderby=evaluation_type/sort_no,sort_no
&$select=tenant_id,nego_type_code,nego_type_name,evaluation_type/evaluation_type_name
&$expand=evaluation_type
Cookie: {{cookie}}
Accept-Language: ko

### Multi Select | NegoType + Outcome
GET {{reviews-service}}/Sc_Nego_Type_Code?
&$orderby=evaluation_type/sort_no,sort_no
&$select=tenant_id,nego_type_code,nego_type_name,evaluation_type
&$expand=nego_parent_type($select=nego_parent_type_name),evaluation_type($select=evaluation_type_name),Outcomes($select=outcome_name)
Cookie: {{cookie}}
Accept-Language: ko

### Multi Select | Outcome with NegoType
GET {{reviews-service}}/Sc_Nego_Type_Code(tenant_id='L2100',nego_type_code='RFQ')/Outcomes?
&$orderby=sort_no
&$select=outcome_name
&$expand=nego_type($select=nego_type_name;$expand=evaluation_type($select=evaluation_type_name))
# &$expand=localized
Cookie: {{cookie}}
Accept-Language: ko
